# Generated by Django 4.1.1 on 2022-10-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Osp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.PositiveSmallIntegerField()),
                ('code_territorial_agency', models.PositiveSmallIntegerField()),
                ('name_territorial_agency', models.CharField(max_length=200, null=True)),
                ('postal_address', models.CharField(max_length=200, null=True)),
                ('chiefs_full_name', models.CharField(max_length=200, null=True)),
                ('telephone_number', models.CharField(max_length=100, null=True)),
                ('fax', models.CharField(max_length=100, null=True)),
                ('phone_help_service', models.CharField(max_length=100, null=True)),
                ('phone_help_service2', models.CharField(max_length=100, null=True)),
                ('working_hours', models.CharField(max_length=500, null=True)),
                ('territory_of_service', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.PositiveSmallIntegerField()),
                ('agency_name', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200)),
                ('number_type', models.CharField(max_length=50, null=True)),
                ('number', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tolist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_territorial_agency', models.CharField(max_length=200)),
                ('abbreviated_name_territorial_agency', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=200)),
                ('post', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('postal_address', models.CharField(max_length=200)),
                ('working_hours', models.CharField(max_length=500)),
                ('oktmo', models.IntegerField(null=True)),
                ('okato', models.IntegerField(null=True)),
                ('okpo', models.IntegerField(null=True)),
                ('ogrn', models.IntegerField(null=True)),
                ('tin', models.IntegerField(null=True)),
                ('faq_number', models.CharField(max_length=100, null=True)),
                ('tel_number_others', models.CharField(max_length=100, null=True)),
                ('fax', models.CharField(max_length=100, null=True)),
                ('url', models.URLField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
    ]
