# Generated by Django 4.1.1 on 2022-10-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_reestr', '0002_osp_created_osp_updated_phonelist_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('name', models.CharField(choices=[('tolist', 'Перечень территориальных органов '), ('phonelist', 'Телефонный справочник работников'), ('osp', 'Перечень отделов судебных приставов')], max_length=10)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
        ),
    ]
