# Generated by Django 4.1.1 on 2022-10-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_reestr', '0003_csvfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tolist',
            name='ogrn',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tolist',
            name='okato',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tolist',
            name='okpo',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tolist',
            name='oktmo',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tolist',
            name='tin',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
